#define EXAMPLE_ESP_WIFI_SSID      "Kite-Config"
#define EXAMPLE_ESP_WIFI_PASS      "password"
#define EXAMPLE_ESP_WIFI_CHANNEL   1
#define EXAMPLE_MAX_STA_CONN       1

#define NUM_CONFIG_FLAOT_VARS 36
#define NUM_ACTUATOR_CONTROL_FLAOT_VARS 36

static const char *TAG = "wifi softAP";
static void (*read_callback)(float*);
static void (*write_callback)(float*);
static void (*actuator_control_callback)(float*);


// ****** GET WEBSITE ******

static esp_err_t kite_config_html_handler(httpd_req_t *req)
{
	esp_err_t error;
    const char* response = (const char*) req->user_ctx;
    error = httpd_resp_send(req, response, strlen(response));
    return error;
}

static const httpd_uri_t kite_config_get_html = {
    .uri       = "/config",
    .method    = HTTP_GET,
    .handler   = kite_config_html_handler,
    /* Let's pass response string in user
     * context to demonstrate it's usage */
    .user_ctx  = "	<!DOCTYPE html>\
<html>\
<head>\
					<style>\
					.button {\
					  border: none;\
					  color: white;\
					  padding: 15px 32px;\
					  text-align: center;\
					  text-decoration: none;\
					  display: inline-block;\
					  font-size: 16px;\
					  margin: 4px 2px;\
					  cursor: pointer;\
					}\
					\
					.button1 {background-color: #4CAF50;} /* Green */\
					\
					.slidecontainer {\
					  width: 100%;\
					}\
\
					.slider {\
					  -webkit-appearance: none;\
					  width: 100%;\
					  height: 25px;\
					  background: #d3d3d3;\
					  outline: none;\
					  opacity: 0.7;\
					  -webkit-transition: .2s;\
					  transition: opacity .2s;\
					}\
\
					.slider:hover {\
					  opacity: 1;\
					}\
\
					.slider::-webkit-slider-thumb {\
					  -webkit-appearance: none;\
					  appearance: none;\
					  width: 25px;\
					  height: 25px;\
					  background: #04AA6D;\
					  cursor: pointer;\
					}\
\
					.slider::-moz-range-thumb {\
					  width: 25px;\
					  height: 25px;\
					  background: #04AA6D;\
					  cursor: pointer;\
					}\
\
					tr td:last-child {\
						width: 1%;\
						white-space: nowrap;\
					}\
					tr td:first-child {\
						width: 1%;\
						white-space: nowrap;\
					}\
					</style>\
</head>\
<body>\
					\
					<span id=\"autogeneratedHTML\"></span>\
					\
					\
					<script>\
						function sendBinary(data, filename, callback){\
							document.body.classList.add('busy-cursor');\
							var xmlhttp;\
							if (window.XMLHttpRequest) {\
								// code for IE7+, Firefox, Chrome, Opera, Safari\
								xmlhttp = new XMLHttpRequest();\
							} else {\
								// code for IE6, IE5\
								xmlhttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\
							}\
							xmlhttp.onreadystatechange = function() {\
								if (this.readyState == 4 && this.status != 200) {\
									document.body.classList.remove('busy-cursor');\
									//document.getElementById(\"txtHint\").innerHTML = this.responseText;\
									alert(\"sending to server failed. Error code is \" + this.status);\
									//don't connect\
								}\
								if(this.readyState == 4 && this.status == 200){\
									document.body.classList.remove('busy-cursor');\
									//write to server successful\
									callback();\
								}\
							};\
\
							xmlhttp.open(\"POST\",filename,true);//can be accessed through \"$_GET\"\
							\
							//This is required to disable caching\
							//disableCache(xmlhttp);\
							\
							xmlhttp.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\
							xmlhttp.send(data);//can be accessed and stored through file_put_contents(filename, file_get_contents('php://input'));\
						}\
						\
						function downloadConfig(){\
							var xhr = new XMLHttpRequest();\
							xhr.open('GET', 'getConfig', true);\
							xhr.responseType = 'arraybuffer';\
							xhr.onload = function(e){\
								var arrayBuffer = xhr.response;\
								if(arrayBuffer){\
									var floatArray = new Float32Array(arrayBuffer);\
									for(let i = 0; i < numConfigValues; i++){\
										configValues[i] = floatArray[i];\
									}\
								}\
							}\
							xhr.send();\
						}\
						\
						function uploadConfig(){\
							const array = ['abcdefgh']; // an array consisting of a single string\
							// TODO: floats to char array.\
							const blob = new Blob(array, { type: \"text/html\" }); // the blob\
							\
							//sendBinary(blob, \"uploadNewConstants\", function(){/*do something on UI side when data has been sent successfully*/});\
						}\
						\
						function controlActuators(elevonLeft, elevonRight, propellerLeft, propellerRight){\
							const array = ['abcdefgh']; // an array consisting of a single string\
							// TODO: floats to char array.\
							const blob = new Blob(array, { type: \"text/html\" }); // the blob\
							\
							//sendBinary(blob, \"uploadNewConstants\", function(){/*do something on UI side when data has been sent successfully*/});\
						}\
						\
						\
						var numConfigValues = 36;\
						var numActuatorsWithoutConfig = 2;\
						var configValues = new Array(numConfigValues).fill(0);\
						\
						var jsFunctions = new Array(numConfigValues + numActuatorsWithoutConfig);\
						\
						\
						// AUTO GENERATED\
						\
						var UIstring = \"\";\
						function addServo(name, index){\
							UIstring += \"\\\
								<tr>\\\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\
									<td><div class=\\\"slidecontainer\\\">\\\
								  		<input type=\\\"range\\\" min=\\\"-90\\\" max=\\\"90\\\" value=\\\"0\\\" class=\\\"slider\\\" id=\\\"slider\" + index + \"\\\">\\\
									</div></td>\\\
									<td><button id=\\\"invert\" + index + \"Button\\\" class=\\\"button button1\\\">Invert</button><button id=\\\"zero\" + index + \"Button\\\" class=\\\"button button1\\\">0</button></td>\\\
								</tr>\\\
							\";\
							jsFunctions[index] = function(){\
								window[\"slider\" + index] = document.getElementById(\"slider\" + index);\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\
								window[\"value\" + index].innerHTML = window[\"slider\" + index].value;\
\
								window[\"slider\" + index].oninput = function() {\
								  window[\"value\" + index].innerHTML = this.value;\
								  //controlActuators(window[\"slider\" + index].value, window[\"slider\" + index].value, 0, 0);\
								}\
								document.getElementById(\"invert\" + index + \"Button\").onclick = function() {\
									configValues[index] *= -1;\
									uploadConfig();\
								}\
								document.getElementById(\"zero\" + index + \"Button\").onclick = function() {\
									window[\"value\" + index].innerHTML = window[\"slider\" + index].value = 0;\
								}\
							};\
						}\
						\
						function addPropeller(name, index){\
							UIstring += \"\\\
								<tr>\\\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\
									<td><div class=\\\"slidecontainer\\\">\\\
								  		<input type=\\\"range\\\" min=\\\"0\\\" max=\\\"90\\\" value=\\\"0\\\" class=\\\"slider\\\" id=\\\"slider\" + index + \"\\\">\\\
									</div></td>\\\
									<td><button id=\\\"zero\" + index + \"Button\\\" class=\\\"button button1\\\">0</button></td>\\\
								</tr>\\\
							\";\
							jsFunctions[index] = function(){\
								window[\"slider\" + index] = document.getElementById(\"slider\" + index);\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\
								window[\"value\" + index].innerHTML = window[\"slider\" + index].value;\
\
								window[\"slider\" + index].oninput = function() {\
								  window[\"value\" + index].innerHTML = this.value;\
								  //controlActuators(window[\"slider\" + index].value, window[\"slider\" + index].value, 0, 0);\
								}\
								//window[\"slider\" + index].onchange = ...\
								\
								document.getElementById(\"zero\" + index + \"Button\").onclick = function() {\
									window[\"value\" + index].innerHTML = window[\"slider\" + index].value = 0;\
								}\
							};\
						}\
						\
						function addSwitch(name, index){\
							UIstring += \"\\\
								<tr>\\\
									<td></td>\\\
									<td></td>\\\
									<td><button id=\\\"switch\" + index + \"Button\\\" class=\\\"button button1\\\">Switch \" + name + \"</button></td>\\\
								</tr>\\\
							\";\
							jsFunctions[index] = function(){\
								\
								document.getElementById(\"switch\" + index + \"Button\").onclick = function() {\
									configValues[index] = (configValues[index] == 0) ? 1 : 0;\
									uploadConfig();\
								}\
							};\
						}\
						\
						function addPIDConstant(name, index){\
							UIstring += \"\\\
								<tr>\\\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\
									<td><button id=\\\"Down\" + index + \"Button\\\" class=\\\"button button1\\\">&#8681</button>\\\
									<button id=\\\"Up\" + index + \"Button\\\" class=\\\"button button1\\\">&#8679</button></td>\\\
									<td></td>\\\
								</tr>\\\
							\";\
							jsFunctions[index] = function(){\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\
								configValues[index] = 1;//TODO remove when real values exist.\
								window[\"value\" + index].innerHTML = configValues[index];\
								\
								document.getElementById(\"Up\" + index + \"Button\").onclick = function() {\
									configValues[index] *= 1.1;\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(2);\
									uploadConfig();\
								}\
								document.getElementById(\"Down\" + index + \"Button\").onclick = function() {\
									configValues[index] /= 1.1;\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(2);\
									uploadConfig();\
								}\
							};\
						}\
						\
						function addDegrees(name, index){\
							UIstring += \"\\\
								<tr>\\\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\
									<td><button id=\\\"Down\" + index + \"Button\\\" class=\\\"button button1\\\">&#8681</button>\\\
									<button id=\\\"Up\" + index + \"Button\\\" class=\\\"button button1\\\">&#8679</button></td>\\\
									<td></td>\\\
								</tr>\\\
							\";\
							jsFunctions[index] = function(){\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\
								configValues[index] = 45;//TODO remove when real values exist.\
								window[\"value\" + index].innerHTML = configValues[index];\
								\
								document.getElementById(\"Up\" + index + \"Button\").onclick = function() {\
									configValues[index] += 1;\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(0);\
									uploadConfig();\
								}\
								document.getElementById(\"Down\" + index + \"Button\").onclick = function() {\
									configValues[index] -= 1;\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(0);\
									uploadConfig();\
								}\
							};\
						}\
						\
						function addHeight(name, index, lowerBound){\
							UIstring += \"\\\
								<tr>\\\
									<td><p>\" + name + \"=<br><span id=\\\"value\" + index + \"\\\"></span></p></td>\\\
									<td><button id=\\\"Down\" + index + \"Button\\\" class=\\\"button button1\\\">&#8681</button>\\\
									<button id=\\\"Up\" + index + \"Button\\\" class=\\\"button button1\\\">&#8679</button></td>\\\
									<td></td>\\\
								</tr>\\\
							\";\
							jsFunctions[index] = function(){\
								window[\"value\" + index] = document.getElementById(\"value\" + index);\
								configValues[index] = 0.5;//TODO remove when real values exist.\
								window[\"value\" + index].innerHTML = configValues[index];\
								\
								document.getElementById(\"Up\" + index + \"Button\").onclick = function() {\
									configValues[index] += 0.5;\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(1);\
									uploadConfig();\
								}\
								document.getElementById(\"Down\" + index + \"Button\").onclick = function() {\
									configValues[index] -= 0.5;\
									configValues[index] = Math.max(lowerBound, configValues[index]);\
									window[\"value\" + index].innerHTML = configValues[index].toFixed(1);\
									uploadConfig();\
								}\
							};\
						}\
						\
						//downloadConfig();\
						\
						//TODO: read configValues from Kite\
						let tableBegin = \"\\\
								<table style=\\\"width:100%\\\">\\\
								<tbody>\\
						\";\
						let tableEnd = \"\\\
								</tbody></table>\\\
						\";\
						\
						UIstring += \"<h3>Actuator Tests and Config</h3>\";\
						UIstring += tableBegin;\
								\
						addServo(\"Brake\", 10);\
						addServo(\"Left Elevon\", 7);\
						addServo(\"Right Elevon\", 8);\
						addSwitch(\"Elevons\", 9);\
						addPropeller(\"Left Prop\", numConfigValues + 0);\
						addPropeller(\"Right Prop\", numConfigValues + 1);\
						addSwitch(\"Props\", 11);\
						\
						UIstring += tableEnd;\
						UIstring += \"<h3>Eight Flying Config</h3>\";\
						UIstring += tableBegin;\
						\
						addHeight(\"sidewaysTime\", 12, 0.5)\
						addHeight(\"turningSpeed\", 13, 0.5)\
						addPIDConstant(\"eight.Z.P\", 27);\
						addPIDConstant(\"eight.Z.D\", 28);\
						addPIDConstant(\"eight.Y.D\", 29);\
						addDegrees(\"eightElevator\", 30);\
						addDegrees(\"transitionYAngle\", 31);\
						addDegrees(\"desiredLineAngle\", 32);\
						addDegrees(\"betaClamp\", 33);//TODO\
						addPIDConstant(\"beta.P\", 34);\
						\
						UIstring += tableEnd;\
						UIstring += \"<h3>Hover Launch Config</h3>\";\
						UIstring += tableBegin;\
						\
						addPIDConstant(\"hover.Y.P\", 14);\
						addPIDConstant(\"hover.Y.D\", 15);\
						addDegrees(\"yAngleOffset\", 16)\
						addPIDConstant(\"hover.Z.P\", 17);\
						addPIDConstant(\"hover.Z.D\", 18);\
						addPIDConstant(\"hover.X.D\", 19);\
						addPIDConstant(\"hover.H.P\", 20);\
						addPIDConstant(\"hover.H.D\", 21);\
						\
						UIstring += tableEnd;\
						UIstring += \"<h3>Landing Config</h3>\";\
						UIstring += tableBegin;\
						\
						addDegrees(\"brake\", 22)\
						addPIDConstant(\"land.Y.P\", 23);\
						addPIDConstant(\"land.Y.D\", 24);\
						addPIDConstant(\"land.X.P\", 25);\
						addHeight(\"landHeight\", 26, -100)\
						\
						UIstring += tableEnd;\
						\
						document.getElementById(\"autogeneratedHTML\").innerHTML = UIstring;\
						\
						for(let i = 0; i < numConfigValues + numActuatorsWithoutConfig; i++){\
							if(typeof jsFunctions[i] === 'function'){\
								jsFunctions[i]();\
							}\
						}\
						\
					</script>\
</body>\
</html>"
};

// ****** GET CONFIG ******

static esp_err_t config_get_handler(httpd_req_t *req)
{
	esp_err_t error;
    float float_values[NUM_CONFIG_FLAOT_VARS];
    
    (*read_callback)(float_values);
    
    char response[NUM_CONFIG_FLAOT_VARS*4];
    memcpy(response, float_values, NUM_CONFIG_FLAOT_VARS*4);
    
    error = httpd_resp_send(req, response, strlen(response));
    return error;
}

static const httpd_uri_t kite_config_get_values = {
    .uri       = "/get_config",
    .method    = HTTP_GET,
    .handler   = config_get_handler,
    /* Let's pass response string in user
     * context to demonstrate it's usage */
    .user_ctx  = NULL
};


// ****** POST CONFIG ******

esp_err_t config_post_handler(httpd_req_t *req)
{
    char content[NUM_CONFIG_FLAOT_VARS*4];

    size_t recv_size = MIN(req->content_len, sizeof(content));

    int ret = httpd_req_recv(req, content, recv_size);
    
    if (ret <= 0) return ESP_FAIL;
    
    //convert to float
    float config_float_values[NUM_CONFIG_FLAOT_VARS];
    memcpy(config_float_values, content, NUM_CONFIG_FLAOT_VARS*4);
    
	//float number0 = config_float_values[0];
	//float number1 = config_float_values[1];
	
	(*write_callback)(config_float_values);
	
	
    /* Send a simple response */
    const char resp[] = "URI POST Response";
    httpd_resp_send(req, resp, HTTPD_RESP_USE_STRLEN);
    return ESP_OK;
}

/* URI handler structure for POST /uri */
httpd_uri_t config_post = {
    .uri      = "/uploadNewConstants",
    .method   = HTTP_POST,
    .handler  = config_post_handler,
    .user_ctx = NULL
};

// ****** POST ACTUATOR CONTROLS ******

esp_err_t control_post_handler(httpd_req_t *req)
{
    char content[NUM_ACTUATOR_CONTROL_FLAOT_VARS*4];

    size_t recv_size = MIN(req->content_len, sizeof(content));

    int ret = httpd_req_recv(req, content, recv_size);
    
    if (ret <= 0) return ESP_FAIL;
    
    //convert to float
    float actuator_control_float_values[NUM_ACTUATOR_CONTROL_FLAOT_VARS];
    memcpy(actuator_control_float_values, content, NUM_ACTUATOR_CONTROL_FLAOT_VARS*4);
    
	//float number0 = config_float_values[0];
	//float number1 = config_float_values[1];
	
	(*actuator_control_callback)(actuator_control_float_values);
	
	
    /* Send a simple response */
    const char resp[] = "URI POST Response";
    httpd_resp_send(req, resp, HTTPD_RESP_USE_STRLEN);
    return ESP_OK;
}

/* URI handler structure for POST /uri */
httpd_uri_t control_post = {
    .uri      = "/uploadControls",
    .method   = HTTP_POST,
    .handler  = control_post_handler,
    .user_ctx = NULL
};



/* This handler allows the custom error handling functionality to be
 * tested from client side. For that, when a PUT request 0 is sent to
 * URI /ctrl, the /hello and /echo URIs are unregistered and following
 * custom error handler http_404_error_handler() is registered.
 * Afterwards, when /hello or /echo is requested, this custom error
 * handler is invoked which, after sending an error message to client,
 * either closes the underlying socket (when requested URI is /echo)
 * or keeps it open (when requested URI is /hello). This allows the
 * client to infer if the custom error handler is functioning as expected
 * by observing the socket state.
 */
esp_err_t http_404_error_handler(httpd_req_t *req, httpd_err_code_t err)
{
    /* For any other URI send 404 and close socket */
    httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "Some 404 error message");
    return ESP_FAIL;
}

static httpd_handle_t start_webserver(void)
{
    httpd_handle_t server = NULL;
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.lru_purge_enable = true;

    // Start the httpd server
    ESP_LOGI(TAG, "Starting server on port: '%d'", config.server_port);
    if (httpd_start(&server, &config) == ESP_OK) {
        // Set URI handlers
        ESP_LOGI(TAG, "Registering URI handlers");
        httpd_register_uri_handler(server, &kite_config_get_html);
        httpd_register_uri_handler(server, &kite_config_get_values);
        httpd_register_uri_handler(server, &config_post);
        httpd_register_uri_handler(server, &control_post);
        #if CONFIG_EXAMPLE_BASIC_AUTH
        httpd_register_basic_auth(server);
        #endif
        return server;
    }

    ESP_LOGI(TAG, "Error starting server!");
    return NULL;
}

static void stop_webserver(httpd_handle_t server)
{
    // Stop the httpd server
    httpd_stop(server);
}

static void disconnect_handler(void* arg, esp_event_base_t event_base,
                               int32_t event_id, void* event_data)
{
    httpd_handle_t* server = (httpd_handle_t*) arg;
    if (*server) {
        ESP_LOGI(TAG, "Stopping webserver");
        stop_webserver(*server);
        *server = NULL;
    }
}

static void connect_handler(void* arg, esp_event_base_t event_base,
                            int32_t event_id, void* event_data)
{
    httpd_handle_t* server = (httpd_handle_t*) arg;
    if (*server == NULL) {
        ESP_LOGI(TAG, "Starting webserver");
        *server = start_webserver();
    }
}









// ACCESS POINT FUNCTIONALITY



static void wifi_event_handler(void* arg, esp_event_base_t event_base,
                                    int32_t event_id, void* event_data)
{
    if (event_id == WIFI_EVENT_AP_STACONNECTED) {
        wifi_event_ap_staconnected_t* event = (wifi_event_ap_staconnected_t*) event_data;
        ESP_LOGI(TAG, "station "MACSTR" join, AID=%d",
                 MAC2STR(event->mac), event->aid);
    } else if (event_id == WIFI_EVENT_AP_STADISCONNECTED) {
        wifi_event_ap_stadisconnected_t* event = (wifi_event_ap_stadisconnected_t*) event_data;
        ESP_LOGI(TAG, "station "MACSTR" leave, AID=%d",
                 MAC2STR(event->mac), event->aid);
    }
}

void wifi_init_softap(void)
{
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    esp_netif_create_default_wifi_ap();

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));

    ESP_ERROR_CHECK(esp_event_handler_instance_register(WIFI_EVENT,
                                                        ESP_EVENT_ANY_ID,
                                                        &wifi_event_handler,
                                                        NULL,
                                                        NULL));

    wifi_config_t wifi_config = {
        .ap = {
            .ssid = EXAMPLE_ESP_WIFI_SSID,
            .ssid_len = strlen(EXAMPLE_ESP_WIFI_SSID),
            .channel = EXAMPLE_ESP_WIFI_CHANNEL,
            .password = EXAMPLE_ESP_WIFI_PASS,
            .max_connection = EXAMPLE_MAX_STA_CONN,
            .authmode = WIFI_AUTH_WPA_WPA2_PSK
        },
    };
    if (strlen(EXAMPLE_ESP_WIFI_PASS) == 0) {
        wifi_config.ap.authmode = WIFI_AUTH_OPEN;
    }

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_AP));
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_AP, &wifi_config));
    ESP_ERROR_CHECK(esp_wifi_start());

    ESP_LOGI(TAG, "wifi_init_softap finished. SSID:%s password:%s channel:%d",
             EXAMPLE_ESP_WIFI_SSID, EXAMPLE_ESP_WIFI_PASS, EXAMPLE_ESP_WIFI_CHANNEL);
}

// init wifi on the esp
// register callbacks
void network_setup_configuring(void (*read_callback_arg)(float*), void (*write_callback_arg)(float*), void (*actuator_control_callback_arg)(float*))
{
	read_callback = read_callback_arg;
	write_callback = write_callback_arg;
	actuator_control_callback = actuator_control_callback_arg;
	static httpd_handle_t server = NULL;
	
    //Initialize NVS
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
      ESP_ERROR_CHECK(nvs_flash_erase());
      ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);
    ESP_LOGI(TAG, "ESP_WIFI_MODE_AP");
    wifi_init_softap();
    
    
    ESP_ERROR_CHECK(esp_netif_init());
    
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, &connect_handler, &server));
    //ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, WIFI_EVENT_STA_DISCONNECTED, &disconnect_handler, &server));
    
    /* Start the server for the first time */
    //server = start_webserver(); // will be started in connect_handler
    
}
